# Generated by Django 4.1.10 on 2023-08-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_savedpost_account_saved_posts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_employer',
            new_name='is_company',
        ),
        migrations.AlterField(
            model_name='account',
            name='saved_posts',
            field=models.ManyToManyField(related_name='saved_by', through='core.SavedPost', to='core.post'),
        ),
    ]
