# Generated by Django 4.1.10 on 2023-08-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_is_employer_account_is_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
