# Generated by Django 4.1.10 on 2023-08-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_comment_is_public_remove_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_report',
        ),
    ]
