# Generated by Django 4.1.10 on 2023-09-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_account_avatar_post_description_post_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['username']},
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['username'], name='core_accoun_usernam_2b7330_idx'),
        ),
    ]
