# Generated by Django 4.1.10 on 2023-09-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_account_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_active',
            new_name='is_report',
        ),
    ]
